# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

default:
 image: europe-west1-docker.pkg.dev/bfb-factory-prd0-f12e/bfb-factory-prod/node-git-style-dict:16-alpine3.15

before_script:
  - git config --global user.email '${GITLAB_USER_EMAIL}'
  - git config --global user.name '${GITLAB_USER_ID}'
  - git config --global http.sslVerify false
  - git clone https://${GITLAB_USER_ID}:${GITLAB_PRIVATE_TOKEN}@${GITLAB_STYLE_DICTIONARY_REPO}
  - git checkout -B main
  - git clean -f 

stages:
  - deploy-to-ios
  - deploy-to-android
    

Style-Dictionary-deploy-iOS:
  stage: deploy-to-ios
  script:  
    - echo "Translating ios tokens"
    - npm run build
    - git clone https://${GITLAB_USER_ID}:${GITLAB_PRIVATE_TOKEN}@${GITLAB_IOS_REPO}
    - cp -a build/ios-swift/. webank-ios/WeBank/Presentation/Resources/Generated/DesignSystem/
    - cd webank-ios/WeBank/Presentation/Resources/Generated/DesignSystem/
    - if [ -n "$(git status --porcelain)" ];
     then
     git checkout -B "Feature/design-token-update";
     git add .;
     git commit -m "${CI_COMMIT_MESSAGE}";
     git push -f --set-upstream https://${GITLAB_USER_ID}:${GITLAB_PRIVATE_TOKEN}@${GITLAB_IOS_REPO} -o merge_request.create -o merge_request.target=develop -o merge_request.description="Update design token set" -o merge_request.label="DesignSystem";
     git config --global http.sslVerify true;
     echo "design tokens pushed to ios successfully";
     else echo "no changes";
     fi


Style-Dictionary-deploy-android:
  stage: deploy-to-android
  script: 
    - echo "Translating android tokens"
    - npm run build
    - git clone -b develop https://${GITLAB_USER_ID}:${GITLAB_PRIVATE_TOKEN}@${GITLAB_ANDROID_REPO} --no-local
    - cp -a build/android/. webank-android/design-system/src/main/java/com/webank/design_system/dictionary/
    - cd webank-android/design-system/src/main/java/com/webank/design_system/dictionary/
    - if [ -n "$(git status --porcelain)" ];
     then
     git checkout -B "feature/design-token-update";
     git add .;
     git commit -m "update design tokens";
     git push -f --set-upstream https://${GITLAB_USER_ID}:${GITLAB_PRIVATE_TOKEN}@${GITLAB_ANDROID_REPO} -o merge_request.create -o merge_request.target=develop -o merge_request.description="Update design token set";
     git config --global http.sslVerify true;
     echo "design tokens pushed to android successfully";
     else echo "no changes";
     fi
