on:
  repository_dispatch:
    types: [update-tokens]

jobs:
  commit_source:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Configure git
        run: |
          git config user.name "Giovanni Martusciello"
          git config user.email "bot@example.com"
  
      - name: Make a commit
        run: |
          echo ${{ github.event.client_payload.tokens }} > file.json
          git add file.json
          git commit -m "Commit by bot"
          git push
      - env:
          MESSAGE: ${{ github.event.client_payload.tokens }}
        run: echo $MESSAGE
