on:
  repository_dispatch:
    types: [update-tokens]

jobs:
  commit_source:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Configure git
        run: |
          git config user.name "Design Token"
          git config user.email "tokens@design.system"
          
      - name: create source.json file
        uses: devops-actions/json-to-file@v1.0.0
        with:
          json: '${{ github.event.client_payload.tokens }}'
          filename: 'json/source.json'
          
      - name: Make a commit
        run: |
          git add json/source.json
          git commit -m "Commit by bot"
          git push
          
      - name: Build transformer
        run: |
          npm run build
          
      - name: Create pull request
        run: |
          git clone https://giovannimartusciello:${{ secrets.API_TOKEN_GITHUB }}@github.com/giovannimartusciello/swiftui-ds-showcase.git --no-local
          cp -a build/ios-swift/. /
          if [ -n "$(git status --porcelain)" ];
          then
          git checkout -B "Feature/design-token-update";
          git add .;
          git commit -m "${CI_COMMIT_MESSAGE}";
          git push -f --set-upstream https://giovannimartusciello:${{ secrets.API_TOKEN_GITHUB }}@github.com/giovannimartusciello/swiftui-ds-showcase.git -o merge_request.create -o merge_request.target=develop -o merge_request.description="Update design token set" -o merge_request.label="DesignSystem";
          git config --global http.sslVerify true;
          echo "design tokens pushed to ios successfully";
          else echo "no changes";
          fi
