on:
  repository_dispatch:
    types: [update-tokens]

jobs:
  commit_source:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Configure git
        run: |
          git config user.name "Design Token"
          git config user.email "tokens@design.system"
          
      - name: create source.json file
        uses: devops-actions/json-to-file@v1.0.0
        with:
          json: '${{ github.event.client_payload.tokens }}'
          filename: 'json/source.json'
          
      - name: Make a commit
        run: |
          git add json/source.json
          git commit -m "Commit by bot"
          git push
          
      - name: Build transformer
        run: |
          npm run build
          
      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'source-folder'
          destination_repo: 'giovannimartusciello/style-dictionary-automator'
          destination_folder: 'swiftuiDSShowcase/Design System'
          destination_base_branch: 'main'
          destination_head_branch: 'feature/design-token-update'
          user_email: 'user-name@paygo.com.br'
          user_name: 'user-name'
