on:
  repository_dispatch:
    types: [update-tokens]

jobs:
  run_build_and_deploy:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Configure git
        run: |
          git config user.name "Design Token"
          git config user.email "tokens@design.system"
          
      - name: create source.json file
        uses: devops-actions/json-to-file@v1.0.0
        with:
          json: '${{ github.event.client_payload.tokens }}'
          filename: 'json/source.json'
          
      - name: Make a commit
        run: |
          git add json/source.json
          git commit -m "Commit by bot"
          git push
          
      - name: Build transformer
        run: |
          npm run build
          
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git clone https://giovannimartusciello:${{ secrets.API_TOKEN_GITHUB }}@github.com/giovannimartusciello/swiftui-ds-showcase.git --no-local
          git status
          cp -a build/ios-swift/. swiftuiDSShowcase/
          cd swiftuiDSShowcase/
          if [ -n "$(git status --porcelain)" ];
          then
          git checkout -B "Feature/design-token-update";
          git add .;
          git commit -m "Design System Tokens Update";
          git config --unset-all http.https://github.com/.extraheader;
          git push -f --set-upstream https://giovannimartusciello:${{ secrets.API_TOKEN_GITHUB }}@github.com/giovannimartusciello/swiftui-ds-showcase.git;
          echo "design tokens pushed to ios successfully";
          else echo "no changes";
          fi
